### PR TITLE
New design for buy/sell order panels

### PR DESCRIPTION
**Pull request by peculiarity**
screenshot_2017-05-17_14-10-35

@gbalabasquer @pimato

### CODE REVIEW

**Comment by pimato** [comment]
Hey @peculiarity 

I am currently testing your implementation, but two major things are not working:

- I cannot define something in the total Inputfield.
- If I click on the BUY MAX button, nothing happens.

**Comment by peculiarity** [comment]
@pimato  impossible

**Comment by pimato** [comment]
Alright I just compared your current implementation with my design:

bildschirmfoto 2017-05-19 um 11 38 31

what needs to be changed:

- a row needs to be higher
- the first cell (price, amount, total) of a raw has too much width
- the last cells (currency indicator) needs more width.
- the available balance indicator shouldn`t use Montserrat, rather Roboto.
- the Buy Button has too much padding, it should be smaller.
- the Hover of the Buy Button should be changed too:

bildschirmfoto 2017-05-19 um 11 43 06

text : #FFFFFF
bg : #5ECFB9
border: #1ABC9C

and please have a look at the picture for comparison

**Comment by pimato** [comment]
looking good now, an additional (and hopefully last) request:

if you click on the button (button pressed) "Max buy" it is currently looking like this:
bildschirmfoto 2017-05-20 um 12 34 09

we should change it to this:
bildschirmfoto 2017-05-20 um 12 41 31


after the button is clicked, it is somehow a white button:
bildschirmfoto 2017-05-20 um 12 34 11

which should be changed to this:
bildschirmfoto 2017-05-20 um 12 41 23

**Pull request merged**
