### PR TITLE
Display transfer history only for a given address

### PR DESCRIPTION
**Pull request by peculiarity**
account1

account2

### CODE REVIEW

**Comment by gbalabasquer** [comment]
@peculiarity @pimato don't we need to take into account the ones received by the person?

**Comment by peculiarity** [comment]
@gbalabasquer I was thinking about it to be honest but not quite sure .. probably might be useful, also it might be useful to put IN/OUT labels like BUY/SELL so it's easier to track the token flow.

**Comment by gbalabasquer** [comment]
Yes I agree, @pimato what do you think?

**Comment by pimato** [comment]
Yes, I agree too. 
I will create a mockup the next days.

**Comment by reverendus** [comment]
I am definitely in favour of this change. But I agree with @gbalabasquer, shouldn't we show both incoming and outgoing transactions of the user?

**Comment by peculiarity** [comment]
image


@gbalabasquer @reverendus 
Changes applied:
 - fetch FROM/TO address transfers.
 - mark is flow as IN/OUT in the UI.

**Pull request merged**
