### PR TITLE
Input fields styling enhancement

### PR DESCRIPTION
**Pull request by peculiarity**
@pimato

### CODE REVIEW

**Comment by gbalabasquer** [comment]
There is something strange, these are my steps:
- I have 7.5 W-ETH allowance already set
- I want to make a buy order of Maker selling 10 W-ETH.
- I click on "Change Allowance"
- The focus works right
- But the input has as place-holder of my 7.5 W-ETH (which I think is fine because is what we have now), but then also has it in the value, so the purpose of the place-holder loses a bit of sense as I still need to remove the previous value.

Maybe thinking it through, would not be better to keep something in the input value but make it the needed amount for the order? Then in this example to have the necessary 10 W-ETH?

**Comment by gbalabasquer** [comment]
My bad about the placeholders, the ones changed are from the new order box, not from allowance one.
Anyway I think we could consider my comment, it would make more sense to show the value of the amount needed for the order.

**Comment by gbalabasquer** [comment]
@pimato What do you think about it?

**Comment by pimato** [comment]
this is a reference to issue: 
https://github.com/OasisDEX/oasis/issues/195

**Comment by pimato** [comment]
with that we should also include issue on the Wrap/Unwrap widget, which should also have placeholders.

issue reference: : https://github.com/OasisDEX/oasis/issues/172

**Comment by pimato** [comment]
we also should include the issue on the transfer widget. The amount inputfield should only have a placeholder 0, not the actually value.

issue reference: https://github.com/OasisDEX/oasis/issues/261

**Comment by pimato** [comment]
regarding the allowance inputfield we are going to do it like @peculiarity and @gbalabasquer suggested. We are going to set the value of the inputfield with the required amount to fill the order.
The issue is reference : https://github.com/OasisDEX/oasis/issues/262

**Comment by peculiarity** [comment]
#195 - Done
#172 - Done
#261 - Done
#262 - Done

**Comment by peculiarity** [comment]
@gbalabasquer @pimato Can check it .. though there is one bug that is breaking the setting of allowance itself. I wrote to Gonzalo that it appears in the commit test web3 of Mariano. Will investigate

**Comment by pimato** [comment]
we should add : 
- [ ] Issue : https://github.com/OasisDEX/oasis/issues/206
- [ ] fix the problem with setting allowance
- [ ] fix the prolems with coloring trades correctly (some sell orders are still black)

**Pull request merged**
