### PR TITLE
Price chart

### PR DESCRIPTION
**Pull request by ferni**
Add price chart

### CODE REVIEW

**Comment by pimato** [comment]
I really like it!

Would it be possible: 

1. to change  line color too: #03A9F4

2. Set a colored area below the line like we have in the volume/depth chart.

3. Make the line have the same thickness (same like volume/depth chart).

4. I think we have here the same problem as in the volume/depth chart. On the right side of the chart the line is a little bit cutted. Could you fix that ? 

group

**Comment by ferni** [comment]
Applied suggested changes:

image

**Comment by nanexcool** [comment]
@ferni @pimato are we good to merge this?

**Comment by ferni** [comment]
@nanexcool Yep.

**Pull request merged**
