### PR TITLE
Possibility to filter orders by opened/closed

### PR DESCRIPTION
**Pull request by peculiarity**
opened
clsoed

@pimato @gbalabasquer

### CODE REVIEW

**Comment by gbalabasquer** [comment]
I just made a test.
User1 made an order selling `0.5 MKR` and buying 0.5 `W-ETH`.
User2 bought that order.
User2 sees that trade in "My closed orders" as a "sell", but for User1 who actually created it, it doesn't show up.

**Comment by gbalabasquer** [comment]
@pimato @peculiarity what was finally the decision taken here?
I see some ways to do it:
1) Keep the dropdown in "My orders" and just show the orders I created in "closed" ones.
2) Same before but showing also the ones that I took (semantically incorrect from my perspective)
3) Same before but renaming the box title to "My trades".
4) Putting the dropdown with my trades (made and took) in the "Market History" box.

It could be also done 1 and 4. Might be a bit redundant but I still think it will be clear.

**Comment by gbalabasquer** [comment]
@pimato nvm, @peculiarity already showed me the issue details.

**Comment by gbalabasquer** [comment]
1)
screen shot 2017-05-09 at 2 52 04 pm

I just created two orders. One buy order and one sell order. Both are showing like sell orders in "My opened trades" and without color.

2) I'd say to make the dropdown text in capital letters or capitalized.

**Comment by pimato** [comment]
- I think with the current changes, we should integrate a clickable list. Users should have the possibility to see there transactions via etherscan.

- I also think we should add consistency in the loading behavour
if the table header in the market history is visible within the loading phase so should be the My Trades widget.

**Pull request merged**
